/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.murmurServer;

import org.murmurServer.domains.Server;
import org.murmurServer.infrastructures.mapper.ServerConfigMapper;
import org.murmurServer.servers.ServerRunning;

import java.nio.file.Paths;

public class App {
    public static void main(String[] args) {
        Runtime.getRuntime().addShutdownHook(new Thread(() -> System.out.println("Au revoir !")));
        System.out.println("[*] Program started");
        String configFolder = Paths.get("src/main/resources/config/").toAbsolutePath().toString();
        ServerConfigMapper mapper = new ServerConfigMapper(configFolder, "server1.json");
        Server server = mapper.getServer();
        ServerRunning serverRunning = new ServerRunning(12020, server);
    }
}
