/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.murmurServer;

import org.murmurServer.domains.Server;
import org.murmurServer.infrastructures.mapper.ServerConfigMapper;
import org.murmurServer.servers.ServerManager;

import java.nio.file.Paths;

public class App {
    public static void main(String[] args) {
        System.out.println("[*] Program started");
        String configFolder = Paths.get("src/main/resources/config/").toAbsolutePath().toString();
        ServerConfigMapper mapper = new ServerConfigMapper(configFolder, "server1.json");
        Server server = mapper.getServer();
        ServerManager serverRunning = new ServerManager(server);
        serverRunning.startServer();
    }
}
