/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.murmurRelay;

import org.murmurRelay.factory.RelayManagerFactory;
import org.murmurRelay.grammar.Protocol;
import org.murmurRelay.handler.RelayManager;
import org.murmurRelay.infrastructures.JsonRepository;
import org.murmurRelay.repositories.IRelayRepository;
import org.murmurRelay.utils.NetChooser;

public class App {
    public static void main(String[] args) {
        try {
            RelayManagerFactory relayFactory = new RelayManagerFactory(new JsonRepository(),new NetChooser(),new Protocol());
            RelayManager relayManager = relayFactory.createAndGetRelayManager();
            relayManager.startRelay();
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
